#!/bin/bash

set -eux

DAY=day$1

# make sure aocdl exists
which "aocdl"

mkdir $DAY
cp templates/* $DAY/

# setup aocdl
# go install github.com/GreenLightning/advent-of-code-downloader/aocdl@latest
# export SESSION_COOKIE=""
# echo "{\"session-cookie\": \"${SESSION_COOKIE}\"}" > ~/.aocdlconfig
